### ISSUE TITLE
Issue with rendered documents

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/hw-02-ajinkyapdeshmukh#1]
Hi ajinkyapdeshmukh10, 

Your rendered HTMLs is substantially longer than it needs to be because you rendered a complete read out of dataframes. This is inadvisable, and I will knock 1 point off for each. You can gain these points back if you address this issue by Friday, October 13th, 11:59pm.

**Comment by ajinkyapdeshmukh10** [comment]
Hi Greg, 
I've addressed the issue and added a glimpse of the dataset instead of the entire dataset which made the rendered HTML longer.
Please find the resolution in the latest commit named "Issue_resolution_v1".

Thanks, 
Ajinkya

**Comment by Gchism94** [comment]
Looks good, you have full credit now.

**Comment by ajinkyapdeshmukh10** [comment]
Thank you,
Ajinkya
